// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package resolver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/haproxytech/models"
)

// NewCreateResolverParams creates a new CreateResolverParams object
// with the default values initialized.
func NewCreateResolverParams() *CreateResolverParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CreateResolverParams{
		ForceReload: &forceReloadDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateResolverParamsWithTimeout creates a new CreateResolverParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateResolverParamsWithTimeout(timeout time.Duration) *CreateResolverParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CreateResolverParams{
		ForceReload: &forceReloadDefault,

		timeout: timeout,
	}
}

// NewCreateResolverParamsWithContext creates a new CreateResolverParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateResolverParamsWithContext(ctx context.Context) *CreateResolverParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CreateResolverParams{
		ForceReload: &forceReloadDefault,

		Context: ctx,
	}
}

// NewCreateResolverParamsWithHTTPClient creates a new CreateResolverParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateResolverParamsWithHTTPClient(client *http.Client) *CreateResolverParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CreateResolverParams{
		ForceReload: &forceReloadDefault,
		HTTPClient:  client,
	}
}

/*CreateResolverParams contains all the parameters to send to the API endpoint
for the create resolver operation typically these are written to a http.Request
*/
type CreateResolverParams struct {

	/*Data*/
	Data *models.Resolver
	/*ForceReload
	  If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.

	*/
	ForceReload *bool
	/*TransactionID
	  ID of the transaction where we want to add the operation. Cannot be used when version is specified.

	*/
	TransactionID *string
	/*Version
	  Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.

	*/
	Version *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create resolver params
func (o *CreateResolverParams) WithTimeout(timeout time.Duration) *CreateResolverParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create resolver params
func (o *CreateResolverParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create resolver params
func (o *CreateResolverParams) WithContext(ctx context.Context) *CreateResolverParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create resolver params
func (o *CreateResolverParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create resolver params
func (o *CreateResolverParams) WithHTTPClient(client *http.Client) *CreateResolverParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create resolver params
func (o *CreateResolverParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create resolver params
func (o *CreateResolverParams) WithData(data *models.Resolver) *CreateResolverParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create resolver params
func (o *CreateResolverParams) SetData(data *models.Resolver) {
	o.Data = data
}

// WithForceReload adds the forceReload to the create resolver params
func (o *CreateResolverParams) WithForceReload(forceReload *bool) *CreateResolverParams {
	o.SetForceReload(forceReload)
	return o
}

// SetForceReload adds the forceReload to the create resolver params
func (o *CreateResolverParams) SetForceReload(forceReload *bool) {
	o.ForceReload = forceReload
}

// WithTransactionID adds the transactionID to the create resolver params
func (o *CreateResolverParams) WithTransactionID(transactionID *string) *CreateResolverParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the create resolver params
func (o *CreateResolverParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WithVersion adds the version to the create resolver params
func (o *CreateResolverParams) WithVersion(version *int64) *CreateResolverParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the create resolver params
func (o *CreateResolverParams) SetVersion(version *int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *CreateResolverParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if o.ForceReload != nil {

		// query param force_reload
		var qrForceReload bool
		if o.ForceReload != nil {
			qrForceReload = *o.ForceReload
		}
		qForceReload := swag.FormatBool(qrForceReload)
		if qForceReload != "" {
			if err := r.SetQueryParam("force_reload", qForceReload); err != nil {
				return err
			}
		}

	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string
		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {
			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}

	}

	if o.Version != nil {

		// query param version
		var qrVersion int64
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := swag.FormatInt64(qrVersion)
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
