// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package maps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/haproxy-data-plane-api-client/models"
)

// DeleteRuntimeMapEntryReader is a Reader for the DeleteRuntimeMapEntry structure.
type DeleteRuntimeMapEntryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRuntimeMapEntryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteRuntimeMapEntryNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteRuntimeMapEntryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteRuntimeMapEntryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteRuntimeMapEntryNoContent creates a DeleteRuntimeMapEntryNoContent with default headers values
func NewDeleteRuntimeMapEntryNoContent() *DeleteRuntimeMapEntryNoContent {
	return &DeleteRuntimeMapEntryNoContent{}
}

/*DeleteRuntimeMapEntryNoContent handles this case with default header values.

Map key/value deleted
*/
type DeleteRuntimeMapEntryNoContent struct {
}

func (o *DeleteRuntimeMapEntryNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/runtime/maps_entries/{id}][%d] deleteRuntimeMapEntryNoContent ", 204)
}

func (o *DeleteRuntimeMapEntryNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRuntimeMapEntryNotFound creates a DeleteRuntimeMapEntryNotFound with default headers values
func NewDeleteRuntimeMapEntryNotFound() *DeleteRuntimeMapEntryNotFound {
	return &DeleteRuntimeMapEntryNotFound{}
}

/*DeleteRuntimeMapEntryNotFound handles this case with default header values.

The specified resource was not found
*/
type DeleteRuntimeMapEntryNotFound struct {
	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *DeleteRuntimeMapEntryNotFound) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/runtime/maps_entries/{id}][%d] deleteRuntimeMapEntryNotFound  %+v", 404, o.Payload)
}

func (o *DeleteRuntimeMapEntryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRuntimeMapEntryDefault creates a DeleteRuntimeMapEntryDefault with default headers values
func NewDeleteRuntimeMapEntryDefault(code int) *DeleteRuntimeMapEntryDefault {
	return &DeleteRuntimeMapEntryDefault{
		_statusCode: code,
	}
}

/*DeleteRuntimeMapEntryDefault handles this case with default header values.

General Error
*/
type DeleteRuntimeMapEntryDefault struct {
	_statusCode int

	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the delete runtime map entry default response
func (o *DeleteRuntimeMapEntryDefault) Code() int {
	return o._statusCode
}

func (o *DeleteRuntimeMapEntryDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/haproxy/runtime/maps_entries/{id}][%d] deleteRuntimeMapEntry default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteRuntimeMapEntryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
