// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package maps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOneRuntimeMapParams creates a new GetOneRuntimeMapParams object
// with the default values initialized.
func NewGetOneRuntimeMapParams() *GetOneRuntimeMapParams {
	var ()
	return &GetOneRuntimeMapParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOneRuntimeMapParamsWithTimeout creates a new GetOneRuntimeMapParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOneRuntimeMapParamsWithTimeout(timeout time.Duration) *GetOneRuntimeMapParams {
	var ()
	return &GetOneRuntimeMapParams{

		timeout: timeout,
	}
}

// NewGetOneRuntimeMapParamsWithContext creates a new GetOneRuntimeMapParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOneRuntimeMapParamsWithContext(ctx context.Context) *GetOneRuntimeMapParams {
	var ()
	return &GetOneRuntimeMapParams{

		Context: ctx,
	}
}

// NewGetOneRuntimeMapParamsWithHTTPClient creates a new GetOneRuntimeMapParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOneRuntimeMapParamsWithHTTPClient(client *http.Client) *GetOneRuntimeMapParams {
	var ()
	return &GetOneRuntimeMapParams{
		HTTPClient: client,
	}
}

/*GetOneRuntimeMapParams contains all the parameters to send to the API endpoint
for the get one runtime map operation typically these are written to a http.Request
*/
type GetOneRuntimeMapParams struct {

	/*Name
	  Map file name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get one runtime map params
func (o *GetOneRuntimeMapParams) WithTimeout(timeout time.Duration) *GetOneRuntimeMapParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get one runtime map params
func (o *GetOneRuntimeMapParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get one runtime map params
func (o *GetOneRuntimeMapParams) WithContext(ctx context.Context) *GetOneRuntimeMapParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get one runtime map params
func (o *GetOneRuntimeMapParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get one runtime map params
func (o *GetOneRuntimeMapParams) WithHTTPClient(client *http.Client) *GetOneRuntimeMapParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get one runtime map params
func (o *GetOneRuntimeMapParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get one runtime map params
func (o *GetOneRuntimeMapParams) WithName(name string) *GetOneRuntimeMapParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get one runtime map params
func (o *GetOneRuntimeMapParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetOneRuntimeMapParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
