// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package acl_runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/haproxy-data-plane-api-client/models"
)

// PostServicesHaproxyRuntimeACLFileEntriesReader is a Reader for the PostServicesHaproxyRuntimeACLFileEntries structure.
type PostServicesHaproxyRuntimeACLFileEntriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostServicesHaproxyRuntimeACLFileEntriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostServicesHaproxyRuntimeACLFileEntriesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostServicesHaproxyRuntimeACLFileEntriesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewPostServicesHaproxyRuntimeACLFileEntriesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPostServicesHaproxyRuntimeACLFileEntriesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostServicesHaproxyRuntimeACLFileEntriesCreated creates a PostServicesHaproxyRuntimeACLFileEntriesCreated with default headers values
func NewPostServicesHaproxyRuntimeACLFileEntriesCreated() *PostServicesHaproxyRuntimeACLFileEntriesCreated {
	return &PostServicesHaproxyRuntimeACLFileEntriesCreated{}
}

/*PostServicesHaproxyRuntimeACLFileEntriesCreated handles this case with default header values.

ACL entry created
*/
type PostServicesHaproxyRuntimeACLFileEntriesCreated struct {
	Payload *models.ACLFileEntry
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesCreated) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/runtime/acl_file_entries][%d] postServicesHaproxyRuntimeAclFileEntriesCreated  %+v", 201, o.Payload)
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ACLFileEntry)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostServicesHaproxyRuntimeACLFileEntriesBadRequest creates a PostServicesHaproxyRuntimeACLFileEntriesBadRequest with default headers values
func NewPostServicesHaproxyRuntimeACLFileEntriesBadRequest() *PostServicesHaproxyRuntimeACLFileEntriesBadRequest {
	return &PostServicesHaproxyRuntimeACLFileEntriesBadRequest{}
}

/*PostServicesHaproxyRuntimeACLFileEntriesBadRequest handles this case with default header values.

Bad request
*/
type PostServicesHaproxyRuntimeACLFileEntriesBadRequest struct {
	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesBadRequest) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/runtime/acl_file_entries][%d] postServicesHaproxyRuntimeAclFileEntriesBadRequest  %+v", 400, o.Payload)
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostServicesHaproxyRuntimeACLFileEntriesConflict creates a PostServicesHaproxyRuntimeACLFileEntriesConflict with default headers values
func NewPostServicesHaproxyRuntimeACLFileEntriesConflict() *PostServicesHaproxyRuntimeACLFileEntriesConflict {
	return &PostServicesHaproxyRuntimeACLFileEntriesConflict{}
}

/*PostServicesHaproxyRuntimeACLFileEntriesConflict handles this case with default header values.

The specified resource already exists
*/
type PostServicesHaproxyRuntimeACLFileEntriesConflict struct {
	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesConflict) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/runtime/acl_file_entries][%d] postServicesHaproxyRuntimeAclFileEntriesConflict  %+v", 409, o.Payload)
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostServicesHaproxyRuntimeACLFileEntriesDefault creates a PostServicesHaproxyRuntimeACLFileEntriesDefault with default headers values
func NewPostServicesHaproxyRuntimeACLFileEntriesDefault(code int) *PostServicesHaproxyRuntimeACLFileEntriesDefault {
	return &PostServicesHaproxyRuntimeACLFileEntriesDefault{
		_statusCode: code,
	}
}

/*PostServicesHaproxyRuntimeACLFileEntriesDefault handles this case with default header values.

General Error
*/
type PostServicesHaproxyRuntimeACLFileEntriesDefault struct {
	_statusCode int

	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the post services haproxy runtime ACL file entries default response
func (o *PostServicesHaproxyRuntimeACLFileEntriesDefault) Code() int {
	return o._statusCode
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesDefault) Error() string {
	return fmt.Sprintf("[POST /services/haproxy/runtime/acl_file_entries][%d] PostServicesHaproxyRuntimeACLFileEntries default  %+v", o._statusCode, o.Payload)
}

func (o *PostServicesHaproxyRuntimeACLFileEntriesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
