// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package spoe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/haproxy-data-plane-api-client/models"
)

// GetAllSpoeFilesReader is a Reader for the GetAllSpoeFiles structure.
type GetAllSpoeFilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllSpoeFilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllSpoeFilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAllSpoeFilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAllSpoeFilesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAllSpoeFilesOK creates a GetAllSpoeFilesOK with default headers values
func NewGetAllSpoeFilesOK() *GetAllSpoeFilesOK {
	return &GetAllSpoeFilesOK{}
}

/*GetAllSpoeFilesOK handles this case with default header values.

Successful operation
*/
type GetAllSpoeFilesOK struct {
	Payload models.SpoeFiles
}

func (o *GetAllSpoeFilesOK) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/spoe/spoe_files][%d] getAllSpoeFilesOK  %+v", 200, o.Payload)
}

func (o *GetAllSpoeFilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSpoeFilesNotFound creates a GetAllSpoeFilesNotFound with default headers values
func NewGetAllSpoeFilesNotFound() *GetAllSpoeFilesNotFound {
	return &GetAllSpoeFilesNotFound{}
}

/*GetAllSpoeFilesNotFound handles this case with default header values.

The specified resource was not found
*/
type GetAllSpoeFilesNotFound struct {
	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

func (o *GetAllSpoeFilesNotFound) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/spoe/spoe_files][%d] getAllSpoeFilesNotFound  %+v", 404, o.Payload)
}

func (o *GetAllSpoeFilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllSpoeFilesDefault creates a GetAllSpoeFilesDefault with default headers values
func NewGetAllSpoeFilesDefault(code int) *GetAllSpoeFilesDefault {
	return &GetAllSpoeFilesDefault{
		_statusCode: code,
	}
}

/*GetAllSpoeFilesDefault handles this case with default header values.

General Error
*/
type GetAllSpoeFilesDefault struct {
	_statusCode int

	/*Configuration file version
	 */
	ConfigurationVersion string

	Payload *models.Error
}

// Code gets the status code for the get all spoe files default response
func (o *GetAllSpoeFilesDefault) Code() int {
	return o._statusCode
}

func (o *GetAllSpoeFilesDefault) Error() string {
	return fmt.Sprintf("[GET /services/haproxy/spoe/spoe_files][%d] getAllSpoeFiles default  %+v", o._statusCode, o.Payload)
}

func (o *GetAllSpoeFilesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	o.ConfigurationVersion = response.GetHeader("Configuration-Version")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
