// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package spoe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/haproxytech/models"
)

// ReplaceSpoeGroupReader is a Reader for the ReplaceSpoeGroup structure.
type ReplaceSpoeGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceSpoeGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceSpoeGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReplaceSpoeGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReplaceSpoeGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewReplaceSpoeGroupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReplaceSpoeGroupOK creates a ReplaceSpoeGroupOK with default headers values
func NewReplaceSpoeGroupOK() *ReplaceSpoeGroupOK {
	return &ReplaceSpoeGroupOK{}
}

/*ReplaceSpoeGroupOK handles this case with default header values.

Spoe groups replaced
*/
type ReplaceSpoeGroupOK struct {
	Payload *models.SpoeGroup
}

func (o *ReplaceSpoeGroupOK) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/spoe/spoe_groups/{name}][%d] replaceSpoeGroupOK  %+v", 200, o.Payload)
}

func (o *ReplaceSpoeGroupOK) GetPayload() *models.SpoeGroup {
	return o.Payload
}

func (o *ReplaceSpoeGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SpoeGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceSpoeGroupBadRequest creates a ReplaceSpoeGroupBadRequest with default headers values
func NewReplaceSpoeGroupBadRequest() *ReplaceSpoeGroupBadRequest {
	return &ReplaceSpoeGroupBadRequest{
		ConfigurationVersion: 0,
	}
}

/*ReplaceSpoeGroupBadRequest handles this case with default header values.

Bad request
*/
type ReplaceSpoeGroupBadRequest struct {
	/*Configuration file version
	 */
	ConfigurationVersion int64

	Payload *models.Error
}

func (o *ReplaceSpoeGroupBadRequest) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/spoe/spoe_groups/{name}][%d] replaceSpoeGroupBadRequest  %+v", 400, o.Payload)
}

func (o *ReplaceSpoeGroupBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceSpoeGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	configurationVersion, err := swag.ConvertInt64(response.GetHeader("Configuration-Version"))
	if err != nil {
		return errors.InvalidType("Configuration-Version", "header", "int64", response.GetHeader("Configuration-Version"))
	}
	o.ConfigurationVersion = configurationVersion

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceSpoeGroupNotFound creates a ReplaceSpoeGroupNotFound with default headers values
func NewReplaceSpoeGroupNotFound() *ReplaceSpoeGroupNotFound {
	return &ReplaceSpoeGroupNotFound{
		ConfigurationVersion: 0,
	}
}

/*ReplaceSpoeGroupNotFound handles this case with default header values.

The specified resource was not found
*/
type ReplaceSpoeGroupNotFound struct {
	/*Configuration file version
	 */
	ConfigurationVersion int64

	Payload *models.Error
}

func (o *ReplaceSpoeGroupNotFound) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/spoe/spoe_groups/{name}][%d] replaceSpoeGroupNotFound  %+v", 404, o.Payload)
}

func (o *ReplaceSpoeGroupNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceSpoeGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	configurationVersion, err := swag.ConvertInt64(response.GetHeader("Configuration-Version"))
	if err != nil {
		return errors.InvalidType("Configuration-Version", "header", "int64", response.GetHeader("Configuration-Version"))
	}
	o.ConfigurationVersion = configurationVersion

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceSpoeGroupDefault creates a ReplaceSpoeGroupDefault with default headers values
func NewReplaceSpoeGroupDefault(code int) *ReplaceSpoeGroupDefault {
	return &ReplaceSpoeGroupDefault{
		_statusCode:          code,
		ConfigurationVersion: 0,
	}
}

/*ReplaceSpoeGroupDefault handles this case with default header values.

General Error
*/
type ReplaceSpoeGroupDefault struct {
	_statusCode int

	/*Configuration file version
	 */
	ConfigurationVersion int64

	Payload *models.Error
}

// Code gets the status code for the replace spoe group default response
func (o *ReplaceSpoeGroupDefault) Code() int {
	return o._statusCode
}

func (o *ReplaceSpoeGroupDefault) Error() string {
	return fmt.Sprintf("[PUT /services/haproxy/spoe/spoe_groups/{name}][%d] replaceSpoeGroup default  %+v", o._statusCode, o.Payload)
}

func (o *ReplaceSpoeGroupDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ReplaceSpoeGroupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Configuration-Version
	configurationVersion, err := swag.ConvertInt64(response.GetHeader("Configuration-Version"))
	if err != nil {
		return errors.InvalidType("Configuration-Version", "header", "int64", response.GetHeader("Configuration-Version"))
	}
	o.ConfigurationVersion = configurationVersion

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
