// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetHAProxyConfigurationParams creates a new GetHAProxyConfigurationParams object
// with the default values initialized.
func NewGetHAProxyConfigurationParams() *GetHAProxyConfigurationParams {
	var ()
	return &GetHAProxyConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHAProxyConfigurationParamsWithTimeout creates a new GetHAProxyConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHAProxyConfigurationParamsWithTimeout(timeout time.Duration) *GetHAProxyConfigurationParams {
	var ()
	return &GetHAProxyConfigurationParams{

		timeout: timeout,
	}
}

// NewGetHAProxyConfigurationParamsWithContext creates a new GetHAProxyConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHAProxyConfigurationParamsWithContext(ctx context.Context) *GetHAProxyConfigurationParams {
	var ()
	return &GetHAProxyConfigurationParams{

		Context: ctx,
	}
}

// NewGetHAProxyConfigurationParamsWithHTTPClient creates a new GetHAProxyConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHAProxyConfigurationParamsWithHTTPClient(client *http.Client) *GetHAProxyConfigurationParams {
	var ()
	return &GetHAProxyConfigurationParams{
		HTTPClient: client,
	}
}

/*GetHAProxyConfigurationParams contains all the parameters to send to the API endpoint
for the get h a proxy configuration operation typically these are written to a http.Request
*/
type GetHAProxyConfigurationParams struct {

	/*TransactionID
	  ID of the transaction where we want to add the operation. Cannot be used when version is specified.

	*/
	TransactionID *string
	/*Version
	  Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.

	*/
	Version *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) WithTimeout(timeout time.Duration) *GetHAProxyConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) WithContext(ctx context.Context) *GetHAProxyConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) WithHTTPClient(client *http.Client) *GetHAProxyConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTransactionID adds the transactionID to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) WithTransactionID(transactionID *string) *GetHAProxyConfigurationParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WithVersion adds the version to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) WithVersion(version *int64) *GetHAProxyConfigurationParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get h a proxy configuration params
func (o *GetHAProxyConfigurationParams) SetVersion(version *int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetHAProxyConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string
		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {
			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}

	}

	if o.Version != nil {

		// query param version
		var qrVersion int64
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := swag.FormatInt64(qrVersion)
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
