// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package spoe_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCommitSpoeTransactionParams creates a new CommitSpoeTransactionParams object
// with the default values initialized.
func NewCommitSpoeTransactionParams() *CommitSpoeTransactionParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CommitSpoeTransactionParams{
		ForceReload: &forceReloadDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCommitSpoeTransactionParamsWithTimeout creates a new CommitSpoeTransactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCommitSpoeTransactionParamsWithTimeout(timeout time.Duration) *CommitSpoeTransactionParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CommitSpoeTransactionParams{
		ForceReload: &forceReloadDefault,

		timeout: timeout,
	}
}

// NewCommitSpoeTransactionParamsWithContext creates a new CommitSpoeTransactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCommitSpoeTransactionParamsWithContext(ctx context.Context) *CommitSpoeTransactionParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CommitSpoeTransactionParams{
		ForceReload: &forceReloadDefault,

		Context: ctx,
	}
}

// NewCommitSpoeTransactionParamsWithHTTPClient creates a new CommitSpoeTransactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCommitSpoeTransactionParamsWithHTTPClient(client *http.Client) *CommitSpoeTransactionParams {
	var (
		forceReloadDefault = bool(false)
	)
	return &CommitSpoeTransactionParams{
		ForceReload: &forceReloadDefault,
		HTTPClient:  client,
	}
}

/*CommitSpoeTransactionParams contains all the parameters to send to the API endpoint
for the commit spoe transaction operation typically these are written to a http.Request
*/
type CommitSpoeTransactionParams struct {

	/*ForceReload
	  If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.

	*/
	ForceReload *bool
	/*ID
	  Transaction id

	*/
	ID string
	/*Spoe
	  Spoe file name

	*/
	Spoe string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) WithTimeout(timeout time.Duration) *CommitSpoeTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) WithContext(ctx context.Context) *CommitSpoeTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) WithHTTPClient(client *http.Client) *CommitSpoeTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForceReload adds the forceReload to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) WithForceReload(forceReload *bool) *CommitSpoeTransactionParams {
	o.SetForceReload(forceReload)
	return o
}

// SetForceReload adds the forceReload to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) SetForceReload(forceReload *bool) {
	o.ForceReload = forceReload
}

// WithID adds the id to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) WithID(id string) *CommitSpoeTransactionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) SetID(id string) {
	o.ID = id
}

// WithSpoe adds the spoe to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) WithSpoe(spoe string) *CommitSpoeTransactionParams {
	o.SetSpoe(spoe)
	return o
}

// SetSpoe adds the spoe to the commit spoe transaction params
func (o *CommitSpoeTransactionParams) SetSpoe(spoe string) {
	o.Spoe = spoe
}

// WriteToRequest writes these params to a swagger request
func (o *CommitSpoeTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ForceReload != nil {

		// query param force_reload
		var qrForceReload bool
		if o.ForceReload != nil {
			qrForceReload = *o.ForceReload
		}
		qForceReload := swag.FormatBool(qrForceReload)
		if qForceReload != "" {
			if err := r.SetQueryParam("force_reload", qForceReload); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param spoe
	qrSpoe := o.Spoe
	qSpoe := qrSpoe
	if qSpoe != "" {
		if err := r.SetQueryParam("spoe", qSpoe); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
