// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package service_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConsulsParams creates a new GetConsulsParams object
// with the default values initialized.
func NewGetConsulsParams() *GetConsulsParams {

	return &GetConsulsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConsulsParamsWithTimeout creates a new GetConsulsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConsulsParamsWithTimeout(timeout time.Duration) *GetConsulsParams {

	return &GetConsulsParams{

		timeout: timeout,
	}
}

// NewGetConsulsParamsWithContext creates a new GetConsulsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConsulsParamsWithContext(ctx context.Context) *GetConsulsParams {

	return &GetConsulsParams{

		Context: ctx,
	}
}

// NewGetConsulsParamsWithHTTPClient creates a new GetConsulsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConsulsParamsWithHTTPClient(client *http.Client) *GetConsulsParams {

	return &GetConsulsParams{
		HTTPClient: client,
	}
}

/*GetConsulsParams contains all the parameters to send to the API endpoint
for the get consuls operation typically these are written to a http.Request
*/
type GetConsulsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get consuls params
func (o *GetConsulsParams) WithTimeout(timeout time.Duration) *GetConsulsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get consuls params
func (o *GetConsulsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get consuls params
func (o *GetConsulsParams) WithContext(ctx context.Context) *GetConsulsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get consuls params
func (o *GetConsulsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get consuls params
func (o *GetConsulsParams) WithHTTPClient(client *http.Client) *GetConsulsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get consuls params
func (o *GetConsulsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetConsulsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
