// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package service_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new service discovery API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for service discovery API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateConsul(params *CreateConsulParams, authInfo runtime.ClientAuthInfoWriter) (*CreateConsulCreated, error)

	DeleteConsul(params *DeleteConsulParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteConsulNoContent, error)

	GetConsul(params *GetConsulParams, authInfo runtime.ClientAuthInfoWriter) (*GetConsulOK, error)

	GetConsuls(params *GetConsulsParams, authInfo runtime.ClientAuthInfoWriter) (*GetConsulsOK, error)

	ReplaceConsul(params *ReplaceConsulParams, authInfo runtime.ClientAuthInfoWriter) (*ReplaceConsulOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateConsul adds a new consul server

  Adds a new Consul server.
*/
func (a *Client) CreateConsul(params *CreateConsulParams, authInfo runtime.ClientAuthInfoWriter) (*CreateConsulCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateConsulParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createConsul",
		Method:             "POST",
		PathPattern:        "/service_discovery/consul",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreateConsulReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateConsulCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*CreateConsulDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  DeleteConsul deletes a consul server

  Deletes a Consul server configuration by it's id.
*/
func (a *Client) DeleteConsul(params *DeleteConsulParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteConsulNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteConsulParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteConsul",
		Method:             "DELETE",
		PathPattern:        "/service_discovery/consul/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteConsulReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteConsulNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteConsulDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetConsul returns one consul server

  Returns one Consul server configuration by it's id.
*/
func (a *Client) GetConsul(params *GetConsulParams, authInfo runtime.ClientAuthInfoWriter) (*GetConsulOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConsulParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getConsul",
		Method:             "GET",
		PathPattern:        "/service_discovery/consul/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetConsulReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConsulOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetConsulDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetConsuls returns an array of all configured consul servers

  Returns all configured Consul servers.
*/
func (a *Client) GetConsuls(params *GetConsulsParams, authInfo runtime.ClientAuthInfoWriter) (*GetConsulsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConsulsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getConsuls",
		Method:             "GET",
		PathPattern:        "/service_discovery/consul",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetConsulsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetConsulsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetConsulsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  ReplaceConsul replaces a consul server

  Replaces a Consul server configuration by it's id.
*/
func (a *Client) ReplaceConsul(params *ReplaceConsulParams, authInfo runtime.ClientAuthInfoWriter) (*ReplaceConsulOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewReplaceConsulParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "replaceConsul",
		Method:             "PUT",
		PathPattern:        "/service_discovery/consul/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &ReplaceConsulReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ReplaceConsulOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*ReplaceConsulDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
