// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPeerSectionsParams creates a new GetPeerSectionsParams object
// with the default values initialized.
func NewGetPeerSectionsParams() *GetPeerSectionsParams {
	var ()
	return &GetPeerSectionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPeerSectionsParamsWithTimeout creates a new GetPeerSectionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPeerSectionsParamsWithTimeout(timeout time.Duration) *GetPeerSectionsParams {
	var ()
	return &GetPeerSectionsParams{

		timeout: timeout,
	}
}

// NewGetPeerSectionsParamsWithContext creates a new GetPeerSectionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPeerSectionsParamsWithContext(ctx context.Context) *GetPeerSectionsParams {
	var ()
	return &GetPeerSectionsParams{

		Context: ctx,
	}
}

// NewGetPeerSectionsParamsWithHTTPClient creates a new GetPeerSectionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPeerSectionsParamsWithHTTPClient(client *http.Client) *GetPeerSectionsParams {
	var ()
	return &GetPeerSectionsParams{
		HTTPClient: client,
	}
}

/*GetPeerSectionsParams contains all the parameters to send to the API endpoint
for the get peer sections operation typically these are written to a http.Request
*/
type GetPeerSectionsParams struct {

	/*TransactionID
	  ID of the transaction where we want to add the operation. Cannot be used when version is specified.

	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get peer sections params
func (o *GetPeerSectionsParams) WithTimeout(timeout time.Duration) *GetPeerSectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get peer sections params
func (o *GetPeerSectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get peer sections params
func (o *GetPeerSectionsParams) WithContext(ctx context.Context) *GetPeerSectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get peer sections params
func (o *GetPeerSectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get peer sections params
func (o *GetPeerSectionsParams) WithHTTPClient(client *http.Client) *GetPeerSectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get peer sections params
func (o *GetPeerSectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTransactionID adds the transactionID to the get peer sections params
func (o *GetPeerSectionsParams) WithTransactionID(transactionID *string) *GetPeerSectionsParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get peer sections params
func (o *GetPeerSectionsParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPeerSectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string
		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {
			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
