// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2019 HAProxy Technologies
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPeerEntryParams creates a new GetPeerEntryParams object
// with the default values initialized.
func NewGetPeerEntryParams() *GetPeerEntryParams {
	var ()
	return &GetPeerEntryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPeerEntryParamsWithTimeout creates a new GetPeerEntryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPeerEntryParamsWithTimeout(timeout time.Duration) *GetPeerEntryParams {
	var ()
	return &GetPeerEntryParams{

		timeout: timeout,
	}
}

// NewGetPeerEntryParamsWithContext creates a new GetPeerEntryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPeerEntryParamsWithContext(ctx context.Context) *GetPeerEntryParams {
	var ()
	return &GetPeerEntryParams{

		Context: ctx,
	}
}

// NewGetPeerEntryParamsWithHTTPClient creates a new GetPeerEntryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPeerEntryParamsWithHTTPClient(client *http.Client) *GetPeerEntryParams {
	var ()
	return &GetPeerEntryParams{
		HTTPClient: client,
	}
}

/*GetPeerEntryParams contains all the parameters to send to the API endpoint
for the get peer entry operation typically these are written to a http.Request
*/
type GetPeerEntryParams struct {

	/*Name
	  PeerEntry name

	*/
	Name string
	/*PeerSection
	  Parent peers name

	*/
	PeerSection string
	/*TransactionID
	  ID of the transaction where we want to add the operation. Cannot be used when version is specified.

	*/
	TransactionID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get peer entry params
func (o *GetPeerEntryParams) WithTimeout(timeout time.Duration) *GetPeerEntryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get peer entry params
func (o *GetPeerEntryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get peer entry params
func (o *GetPeerEntryParams) WithContext(ctx context.Context) *GetPeerEntryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get peer entry params
func (o *GetPeerEntryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get peer entry params
func (o *GetPeerEntryParams) WithHTTPClient(client *http.Client) *GetPeerEntryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get peer entry params
func (o *GetPeerEntryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get peer entry params
func (o *GetPeerEntryParams) WithName(name string) *GetPeerEntryParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get peer entry params
func (o *GetPeerEntryParams) SetName(name string) {
	o.Name = name
}

// WithPeerSection adds the peerSection to the get peer entry params
func (o *GetPeerEntryParams) WithPeerSection(peerSection string) *GetPeerEntryParams {
	o.SetPeerSection(peerSection)
	return o
}

// SetPeerSection adds the peerSection to the get peer entry params
func (o *GetPeerEntryParams) SetPeerSection(peerSection string) {
	o.PeerSection = peerSection
}

// WithTransactionID adds the transactionID to the get peer entry params
func (o *GetPeerEntryParams) WithTransactionID(transactionID *string) *GetPeerEntryParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the get peer entry params
func (o *GetPeerEntryParams) SetTransactionID(transactionID *string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPeerEntryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// query param peer_section
	qrPeerSection := o.PeerSection
	qPeerSection := qrPeerSection
	if qPeerSection != "" {
		if err := r.SetQueryParam("peer_section", qPeerSection); err != nil {
			return err
		}
	}

	if o.TransactionID != nil {

		// query param transaction_id
		var qrTransactionID string
		if o.TransactionID != nil {
			qrTransactionID = *o.TransactionID
		}
		qTransactionID := qrTransactionID
		if qTransactionID != "" {
			if err := r.SetQueryParam("transaction_id", qTransactionID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
